# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cuopt-mps-parser
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  dynamic_linking:
    overlinking_behavior: error
  prefix_detection:
    # See https://github.com/rapidsai/build-planning/issues/160
    ignore:
      - lib/python${{ py_version }}/site-packages/data_model/libmps_parser.so
  script:
    content: |
      ./build.sh cuopt_mps_parser

requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - libmps-parser =${{ version }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
  host:
    - cython >=3.0.0
    - libmps-parser =${{ version }}
    - pip
    - python =${{ py_version }}
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - scikit-build-core >=0.10.0
  run:
    - numpy >=1.23,<3.0a0
    - python

tests:
  - python:
      imports:
        - cuopt_mps_parser
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuopt/cuopt/linear_programming/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuopt/cuopt/linear_programming/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cuopt/cuopt/linear_programming/pyproject.toml").project.description }}
